export const FONTS = {
    latoRegular: 'Lato-Regular',
    latoSemiBold: 'Lato-Semibold',
    latoLight: 'Lato-Light',
    latoMedium: 'Lato-MediumItalic',
    pBlack: 'Poppins-Black',
    pBlackItalic: 'Poppins-BlackItalic',
    pBold: 'Poppins-Bold',
    pBoldItalic: 'Poppins-BoldItalic',
    pExtraLight: 'Poppins-ExtraLight',
    pRegular: 'Poppins-Regular',
    pSemiBold: 'Poppins-SemiBold',
    size11: 11,
    size12: 12,
    size14: 14,
    size16: 16,
    size18: 18,
    size20: 20,
    size22: 22,
    size24: 24,
    size26: 26,
    size28: 28,
    size30: 30,
    size32: 32,
    size36: 36,
    size42: 42,
    size78: 78,
  };
  